version: "3.8"

x-common-build:
  &common-build
  build:
    context: .
    dockerfile: Dockerfile.django
    args:
      APPENV: ${COMPOSE_PROFILES:-local}  # Default to 'local' if not specified

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./notification/media/:/media/
      - ./notification/static/:/static/
      - ./nginx/log:/var/log/nginx/

  backend:
    <<: *common-build
    volumes:
      - ./notification:/project/notification
    depends_on:
      - postgres
    platform: linux/amd64
    env_file: .env.${COMPOSE_PROFILES:-local}
    profiles: ["local", "test"]
  
  postgres:
    image: postgres:15.4
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    env_file: .env.${COMPOSE_PROFILES:-local}
    profiles: ["local", "test"]

# Usage:
# COMPOSE_PROFILES=local docker-compose up --build
